[tool]
id = "org.lp3bridge.whatsapp"
label = "WhatsApp"
versionCode = 13
versionName = "0.11.2"
permissions = ["android.permission.INTERNET", "android.permission.RECORD_AUDIO", "android.permission.CAMERA"]
capabilities = []
serverPackage = "com.lightos"
orientation = "portrait"
